# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dice and Disadvantages
tagline:          'A D&D Blog'
description:      'A blog tracking the travels of adventurers in the Sword Coast and Northern Lands as they deal with a Giant problem'
url:              https://mitchkeenan.com/dnd/
baseurl:          https://mitchkeenan.com/dnd/

author:
  name:           'Mitch Keenan'
  url:            https://mitchkeenan.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/konamacona/dnd
